### ISSUE TITLE
Run acceptance tests through helm

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#1762]
The acceptance tests are currently wired together through docker-compose. Running them therefore requires many environment variables to be defined. If the tests were run through helm (`helm test`), the necessary information or running the tests could just be taken from the chart values.

The steps here would be:
- creating a test user
- running the acceptance tests using this user
- deleting the test user (also in gitlab) after successful test execution

Also, for dev or ci deployments there should be an option to run the tests using another deployment (and an existing user from there) as identity provider.

**Comment by aledegano** [comment]
Regarding the automated user creation and deletion I believe that we should have a discussion because there are several moving parts involved in that.
To start these are some facts, as I understand them:

- When registering an user for the first time, through the Renku UI an email verification is required. The acceptance tests do not handle this.

- Once the user is registered on Renku (Keycloak), Renku must be allowed as an application of Gitlab to enable OIDC authentication 

- As per renku#1804, currently removing an account requires multiple steps across different components

- When Renku is configured to use another deployment as Identity Provider (as for personal dev deployments), the registration of the user is automated in the tests, if the user already exists in the upstream provider (however there cannot be automatically created)

Given the above I only see two options:

1. Handle the test user manually, out-of-band with respect to the tests, documenting how a Renku operator is supposed to set it up
2. Create issues to tackle the above points, distributing them on the competent Renku sub-teams to get to a fully automatable user creation/destruction within the tests

Personally I lean toward the option one as I am not convinced that option 2 brings enough value for the effort I am expecting.

@SwissDataScienceCenter/yat what do you guys think?
