### ISSUE TITLE
renkulab "new project" form complains about contributed project template

### ISSUE THREAD

**Issue by ltalirz** [SwissDataScienceCenter/renku#2070]
**Describe the bug**

This concerns the "new project" form https://renkulab.io/projects/new on renkulab

When using my fork https://github.com/ltalirz/contributed-project-templates  of the custom project templates repository https://github.com/SwissDataScienceCenter/contributed-project-templates, I get the error
"There is no manifest file "manifest.yaml" despite the manifest file being there and identical to the one from the main contributed templates repo

![image](https://user-images.githubusercontent.com/1053245/114517233-703ec780-9c3e-11eb-9ed4-e9c4cb49e233.png)

Weirdly enough, 
 * the problem does not occur when using the main branch on the official https://github.com/SwissDataScienceCenter/contributed-project-templates repository
 * I've pushed this branch to the "test" branch on my fork. Here, the problem *does* occur, despite my "test" branch being identical 

**To Reproduce**
See above

**Expected behavior**
No error should be raised as the manifest.yaml file is there, and identical to the one from the main repo.

**Additional context**
@rokroskar mentioned 
> we found a bug actually in our service endpoint that processes the templates so this is probably related. [...] We have already implemented a fix but it hasn’t been released yet, hopefully this week. 

Please give me a ping when this is fixed

**Comment by lorenzo-cavazzi** [comment]
Thank you for reporting this!
As Rok mentioned, there is a regression in the custom template in this release. Specifically, the reference provided in the `Repositore Reference` field is ignored, and the template is fetched for the default branch instead (i.e. `main`).

As a temporary workaround, you could try to fork the repo and merge the `test` branch into `main`. I've quickly tried here and it seems to work https://github.com/lorenzo-cavazzi/contributed-project-templates

![Screenshot_20210413_160746](https://user-images.githubusercontent.com/43481553/114566284-66cf5280-9c72-11eb-841a-0c93f9ddf2bf.png)

**Comment by ltalirz** [comment]
Ah great, thanks for testing!

**Comment by pameladelgado** [comment]
@ltalirz we have made recently a release that includes a fix for this issue. 
You should now be able to fetch your contributed project templates, e.g. using this link to create [an AiiDA renku project](https://renkulab.io/projects/new?data=eyJ0aXRsZSI6InRlc3QgY3VzdG9tIHRlbXBsYXRlIiwidXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL2x0YWxpcnovY29udHJpYnV0ZWQtcHJvamVjdC10ZW1wbGF0ZXMiLCJyZWYiOiJ0ZXN0IiwidGVtcGxhdGUiOiJDdXN0b20vYWlpZGEifQ%3D%3D) works for me:
![Screenshot from 2021-04-26 15-08-38](https://user-images.githubusercontent.com/43743260/116087584-4c996980-a6a1-11eb-9216-3a3ac212ec9c.png)
Please let us know if this is OK for you, so that we close this issue.

**Comment by ltalirz** [comment]
thanks @pameladelgado - I confirm that the issue is fixed
