### ISSUE TITLE
Improve user docs

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#300]
The user documentation should include some material that explains the basic concepts of Renku. This should ideally be done in a progressively technical manner, starting with a very high-level overview of how to obtain reproducible analysis, to some more details about the technology behind it (e.g. CWL).

- [x] explain why we want to record lineage (#302)
- [x] version control
- [x] combining version control and lineage in renku (include high-level explanation of workflows/CWL?) (#418)

**Comment by fgeorgatos** [comment]
@rokroskar : thank you for opening this. I'd like to offer an example as regards the lineage:
* https://en.wikipedia.org/wiki/RANDU

"widely considered to be one of the most ill-conceived random number generators ever designed" and it has been used by several teams in physics for almost a decade. Good example of why keeping the details available about what you do and how you do it, so that it then becomes possible to re-validate existing research efforts, even if you have good reasons to believe that this will not be really needed.

**Comment by rokroskar** [comment]
Thanks @fgeorgatos - I've already started work on this but needs a patch in sphinx. You can look at https://github.com/rokroskar/renku/tree/docs but I need to add my sphinx patch before it can build the graphs.

**Comment by rokroskar** [comment]
Sorry, the actual doc is here: https://github.com/rokroskar/renku/blob/docs/docs/user/reproducibility.rst

**Comment by erbou** [comment]
@rokroskar 
In first steps, next to "Behind the scenes, Renku is using a GitLab server to manage the repositories. In order to push to the server you need to add a valid ssh key to your account. To do this, log in to gitlab (e.g. http://gitlab.renku.build) and follow the GitLab instructions."

This should be moved to a different section for creating new users and configuring their profiles. AFAIK, the ssh key set-up is needed only for new users and when they use a new machine.

**Comment by erbou** [comment]
The first steps starts with the CLI. This typical of how we manage projects on github/lab. Because they don't provide a development, it has to be done elsewhere, and we've been trained to follow this flow.

However Renku provides everything I need for developing and running my data science projects. And under this new environment I find myself wanting to create my projects, import the data and run the notebooks directly on the cloud. Currently, I am able to do that, but it is not straightforward, you have to watch your steps  and it is not well documented.

I suggest that we rewrite the first steps to follow the flows where everything is done on the cloud. The current next steps could be moved into a 'next-steps' about the CLI.

**Comment by leafty** [comment]
@erbou this converges with the new first page from PR #355

**Comment by rokroskar** [comment]
closing for now -- partially resolved in #418
