### ISSUE TITLE
Make cypress acceptance tests more robust to previous failures

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku#3009]
Sometimes a cypress acceptance test runs and leaves a zombie session around that causes problems for later runs.

We should make the logic that connects to a session also consider the project (which should be unique per run), since this will make the test more robust.

**Comment by lorenzo-cavazzi** [comment]
To add more context: we are checking that we can start a session on a project, and terminate it. We give it for granted that no other sessions should be running. This fails when another process leaves sessions (e.g. something failed and the previous session is still running).

We should update the logic so that:
- We actually verify no sessions _for the specific project we are working with_  are running before starting a new session there. If that's not the case, we should terminate them beforehand.
- Verify the tests check only running sessions for the target project, not all the test user sessions.
