### ISSUE TITLE
Outdated collaboration page in RenkuLab tutorial

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku#3026]
Link to doc page: https://renku.readthedocs.io/en/latest/tutorials/first_steps/11_sharing_is_caring.html

This page contains outdated information about the "Collaboration" tab which does not exist currently.
The page could be removed or updated to reflect the current user interface of Renku (see screenshot).

![image](https://user-images.githubusercontent.com/951086/230066813-e97c4411-89c9-4e0a-a97d-e5d85aa75fe5.png)

**Comment by lorenzo-cavazzi** [comment]
@rokroskar I suggest dropping that section entirely since we don't explicitly expose the "issues" and "merge requests" on the UI anymore; we have a link to the GitLab pages from the project, and users can rely on that but we probably don't want to encourage its use by having a dedicated page on the docs.

**Comment by rokroskar** [comment]
I believe this is no longer a problem, was fixed in https://github.com/SwissDataScienceCenter/renku/pull/3196
