### ISSUE TITLE
Large csv file not fully uploaded

### ISSUE THREAD

**Issue by sjinko** [SwissDataScienceCenter/renku#478]
I tried to upload a large csv file in a data folder, using 1. drag and drop and 2. with terminal commands.
The file is 64MB, representing data in three columns and 2'623'194 rows.

The resulting file in the data folder corresponds to the first few hundred thousand rows of my original file. Several thousand rows are missing.

**Comment by rokroskar** [comment]
Hi @sjinko thanks for reporting this -- could you give some more details about how you tried to do this from the terminal?

**Comment by sjinko** [comment]
I used the following command to upload the .csv data file in my project's
data folder using the JupyterLab Terminal in RenkuLab:
The URL pointed to a file on my Dropbox cloud.

renku dataset add [mydatafile] https://[mybigcsvfile].csv

**Comment by rokroskar** [comment]
It may be that the files were not properly added to git LFS (Large File Storage). We use git-LFS to handle  data files alongside code in repositories, but this extension must be enabled when running renku commands. In order to avoid problems in the future, make sure you run `git lfs install --local` in your repository (note: to avoid LFS issues, you can change the image used in your `Dockerfile` to `renku/singleuser:latest`). 

To properly configure your repository and use LFS for your data files, you have two options: 

1. use `git lfs migrate` (https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs) to move the current files to LFS. You then need to repeat the `renku dataset add <dataset> <URL>` command to re-download the files. 
2. use `git reset --hard` to move your repository back to the commit *before* the files were added. Then add the files again.

Before you do either of these, make sure you run `git lfs install --local` in your repository directory. Once you are done, you can use `git lfs ls-files` to see which files are managed by LFS. 

If you are adding data without using `renku` commands, you need to tell LFS to track your files. To do this, use `git lfs track <path-to-file>` *before* adding the file to git. Afterwards, commit normally and do `git lfs ls-files` -- you should see the files listed. 

With either of these options you need to rewrite some part of the repository so you will need to force-push to the server. By default this is not allowed (the master branch is protected) but you can turn off branch protection temporarily by:

1. In renkulab, click on the `View Project in GitLab` button
2. Once in GitLab, go to `Settings -> Repository -> Protected Branches` and unprotect master. 

Then in your terminal session where you have the cleaned up repository, do `git push --force origin master`.

**Comment by rokroskar** [comment]
Hi @sjinko, did you manage to fix the issue with the file upload?

**Comment by rokroskar** [comment]
@sjinko I'm assuming this is either no longer a problem or it's no longer relevant - could you please confirm and close the issue if that's the case?
