### ISSUE TITLE
Define the dataset backend API

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#593]
Gathering ideas here for a specification of an API to bring data into Renku. 

We have concluded to 

* keep the `Dataset` abstraction
* not create a confusing second abstraction of `Data` 
* provide a simple command to import single files - this should be the starting point of the backend API

There are a few different scenarios to consider.

## import data from a URL

A single file from a URL. The URL is fully qualified, meaning that a `wget <URL>` will download the file under the correct filename. The "URL" can be a local filesystem path. 

```
renku dataset add <URL> <dataset-name>
```

will result in the file being added to `data/<dataset-name>` and to the dataset metadata at `.renku/datasets/refs/<dataset-name>/metadata.yml`. The 

## import from a git repository

A *single* file/path is *added* to a dataset from any git repository:

```
renku dataset add <repo-URL> my-dataset --path <path-in-repo>
```

by default the `<path-in-repo>` is placed in `data/my-dataset/`. Note that in the current implementation the `--target` option does what `--path` would above but it uses the full relative path of the source file in the source repository. 

## import from a renku repository

An *entire* dataset is *imported* from a renku repository

```
renku dataset import --name <dataset-name> <repo-URL>
```

This should grab the dataset `<dataset-name>` from the renku repository along with any associated metadata, i.e. the file  `.renku/datasets/refs/<dataset-name>/metadata.yml`, and bring it to the current project. It should also fetch all the relevant files. 

If a renku repository URL is provided without a dataset name, *all* of the datasets found in that repository are imported, e.g.

```
renku dataset import <repo-URL>
```

## import from a data repository e.g. zenodo or dataverse

*Import* of an *entire* dataset from the *external* (non-renku) data repository including all the relevant metadata and store it in `.renku/datasets/<dataset-id>/metadata.yml`

## Fetching of data

For imports from git repositories the current behavior is to clone the repository as a submodule to the `.renku/vendors` directory and symlink the requested files to the destination in the project path. This is done so that we can easily generate the full lineage for data imported from other renku projects. 

see also https://github.com/swissdatasciencecenter/renku-python/issues/239 for an old discussion on this topic.

**Comment by rokroskar** [comment]
So after discussing this IRL, the conclusion is to:

* keep the `Dataset` abstraction
* not create a confusing second abstraction of `Data` 
* provide a simple command to import single files - this should be the starting point of the backend API

The last point is currently achieved already by doing

```
renku dataset add my-dataset <URL>
```

if `my-dataset` doesn't exist, it is created and the data under `<URL>` is added there. Does this seem like an OK solution for now? cc @SwissDataScienceCenter/renku-devs

**Comment by rokroskar** [comment]
More fine-tuning of this API. There are a few different scenarios to consider.

## import from a URL

A single file from a URL. The URL is fully qualified, meaning that a `wget <URL>` will download the file under the correct filename. The "URL" can be a local filesystem path. 

```
renku dataset add <URL> <dataset-name>
```

will result in the file being added to `data/<dataset-name>` and to the dataset metadata at `.renku/datasets/refs/<dataset-name>/metadata.yml`. The 

## import from a git repository

A *single* file/path is *added* to a dataset from any git repository:

```
renku dataset add <repo-URL> my-dataset --path <path-in-repo>
```

by default the `<path-in-repo>` is placed in `data/my-dataset/`. Note that in the current implementation the `--target` option does what `--path` would above but it uses the full relative path of the source file in the source repository. 

## import from a renku repository

An *entire* dataset is *imported* from a renku repository

```
renku dataset import --name <dataset-name> <repo-URL>
```

This should grab the dataset `<dataset-name>` from the renku repository along with any associated metadata, i.e. the file  `.renku/datasets/refs/<dataset-name>/metadata.yml`, and bring it to the current project. It should also fetch all the relevant files. 

## import from a data repository e.g. zenodo or dataverse

*Import* of an *entire* dataset from the *external* (non-renku) data repository including all the relevant metadata and store it in `.renku/datasets/<dataset-id>/metadata.yml`

## Fetching of data

For imports from git repositories the current behavior is to clone the repository as a submodule to the `.renku/vendors` directory and symlink the requested files to the destination in the project path. This is done so that we can easily generate the full lineage for data imported from other renku projects.

**Comment by mohammad-sdsc** [comment]
This is great! I have some questions/comments:
* What is the difference between `add` and `import`? If this is a subtle difference, I would suggest to unify these two and give a single command to the user (e.g. a Renku repo and a git repo have many things in common). Minor differences can be handled by various command-line options.
* Command syntax across `add` and `import` is not consistent; in `import` dataset name comes before URL while in `add` this is reverse.
* It would be good to document the behavior in some corner cases. For example, what should happen if we import a whole Renku repo when there existing datasets whit conflicting names.

**Comment by ableuler** [comment]
I like the separation of `import`ing an entire dataset that is existing elsewhere and `add`ing data to an already existing local dataset. One way to make this even clearer could be to make the import of an entire dataset an option of dataset creation:
```
renku dataset create --import-from <repo-URL>
```
However, this might be even more confusing...

**Comment by pameladelgado** [comment]
as I see it, having a distinction between `import` and `add` is useful:
* the `import` is for *existent* Renku data, while `add` is adding *new* data to Renku. By that definition I would maybe put Zenodo and Dataverse as `add` rather than `import`.
* `import` would always create a new dataset, while `add` will only add the data to a previously created dataset.

I also have a question: I'm not sure how the lineage is handled in the case of an import, what would happen when you import a dataset from another project?

+1 for the corner cases

**Comment by ciyer** [comment]
@pameladelgado What are the semantics for `add` and providing a url to existing Renku data? Would that behave differently from `import`?

**Comment by pameladelgado** [comment]
@ciyer what I said in my comment above is what I think it could be. For me, `import` would be like executing `renku create` and `renku add` while `add` would be just adding the data.
I guess the question is if/when it makes sense to do multiple imports from different sources to the same dataset, I would expect that's not too often/needed but I might be wrong.
Maybe people with more user experience could say what makes more sense for the users, @erbou ?

**Comment by rokroskar** [comment]
OK many good comments here, thanks! I'll try to address them top to bottom:

* regarding the difference between `add` and `import` @pameladelgado has the right idea - I wanted to differentiate between importing an existing dataset with associated metadata and adding to a dataset that the user created. I think the differentiation comes about because in the case of `add` we are creating new content, i.e. new metadata and in the case of `import` we are keeping it as is

* yes, please add a wishlist for corner cases that need to be documented. I will make an "open questions" section at the bottom of the description

* @ciyer yes I will move the text from my comment to the top-level issue description

* running `add` on data from an existing project is a bit of a strange case - there, I think we would want to preserve some but potentially not all metadata. Not sure exactly though, I think the answer to this question will crystalize a bit better once we try to actually do this. 

* @ableuler using an `--import` flag to `create` is not a bad idea -- it would certainly remove one command which is a 👍

**Comment by mohammad-sdsc** [comment]
Regarding the difference between `add` and `import`:
This means that as a user I must know which dataset already has metadata (TBH IDK if this is a good assumption or not) and must be careful not to use `add` with something that has metadata (or otherwise I lose its metadata). I'd rather have a single command (e.g. `import`) that imports everything and uses existing metadata when available and creates new metadata when needed. In case I don't want the metadata to be imported, a `--discard-metadata` option is enough to tell Renku to not to import dataset's metadata.
But again it's me :). Maybe real Renku users have a different mindset; it's a good idea to get insight from their point of view.

**Comment by rokroskar** [comment]
No I think the metadata/no-metadata distinction is for us - to the user it's (I think) pretty clear. If I am *creating* a dataset I do:

```
renku dataset create <dataset>
renku dataset add <URL> <dataset>
```

If I want to get a *previously created* dataset I do

```
renku dataset import <URL>
```

**Comment by cchoirat** [comment]
Ok...  How about:

```
renku dataset add <dataset>
renku dataset add <URL> <dataset>
renku dataset add <URL>
```

More is less?

**Comment by rokroskar** [comment]
Can you clarify a bit what those should do?

**Comment by cchoirat** [comment]
Not sure I'm reading it right, but is there really a fundamental difference that would require two verbs?  Can `renku add` detect the nature of the arguments?

**Comment by rokroskar** [comment]
sure it can, but I was trying to make less magic happen not more. Is it more confusing to remember the order of arguments or the names of subcommands?

**Comment by cchoirat** [comment]
how about flags?

**Comment by rokroskar** [comment]
Flags are usually for optional things and should have sensible defaults so they shouldn't be needed most of the time.

**Comment by rokroskar** [comment]
Alright, so after discussing it a bit more with @ciyer and @cchoirat how about:

```
renku dataset create <dataset>  # creates an empty dataset
renku dataset create --from <URL> <dataset>  # imports an existing dataset
renku dataset add-data <URL> <dataset>  # adds data from <URL> to <dataset>
```

The semantics of `renku dataset create --from <URL> <dataset>` are:

* if `<URL>` is a renku repo, import the dataset of the name `<dataset>`
* if `<URL>` is a resolvable doi from a supported provider, import that data under a dataset of name `<dataset>` in the current project
* if neither of the above, raise an error

For `renku dataset add-data <URL> <dataset>`:

* if `<dataset>` does not exist in the current project, create it
* if `<URL>` points to a git repository, require that a `--path` flag is used to specify which path to import
* if `<URL>` can be downloaded, download it under `<dataset>` and save the URL in the metadata

**Comment by jsam** [comment]
> ```
> renku dataset create <dataset>  # creates an empty dataset
> renku dataset create --from <URL> <dataset>  # imports an existing dataset
> renku dataset add-data <URL> <dataset>  # adds data from <URL> to <dataset>
> ```

I fail to see, how is this better from what we currently have? Honestly, I find it more confusing and hard to type/use.

**Comment by rokroskar** [comment]
fewer commands?

**Comment by cchoirat** [comment]
Not totally convinced either.  Quoting @mohammad-sdsc, "If this is a subtle difference, I would suggest to unify these two and give a single command to the user".

**Comment by rokroskar** [comment]
ok, to me importing a complete dataset, potentially something with a DOI is a fundamentally different thing than loosely assembling some data into a dataset for my own consumption. That's why I'd like to separate the concept of _importing a dataset_ from _adding data to a dataset_.

**Comment by jsam** [comment]
New dataset API needs to take into account the requested features which we have in our backlog, not make adding them more convoluted. I agree with the @rokroskar proposal cause it cleanly separates magic and it's pretty straightforward to use, and more importantly it's easy to extend with new features.

Add and importing are two different topics and should be kept separated.

**Comment by rokroskar** [comment]
> I agree with the @rokroskar proposal

you mean the one at the top of this thread? The modification to make there is maybe to use `renku dataset add-data` instead of `renku dataset add`.

**Comment by jsam** [comment]
Which is not clean.  If we are talking already about data why do you need to say it again in subcommand?

**Comment by rokroskar** [comment]
to avoid confusion between `add` and `import`? One could also think that `import` has to do with adding units of data to a dataset.

**Comment by erbou** [comment]
Nice comments here. I personally prefer the `create --from` because in my opinion the intent is more clear. In particular, I should not try to create a dataset that already exists, which I would be tempted to do with `import`

**Comment by cchoirat** [comment]
> ok, to me importing a complete dataset, potentially something with a DOI, is a fundamentally different thing than loosely assembling some data into a dataset for my own consumption. That's why I'd like to separate the concept of _importing a dataset_ from _adding data to a dataset_.

It assumes that users are well-versed in DOIs, etc.  Can we have a poll with our own data scientists maybe?

**Comment by jsam** [comment]
> to avoid confusion between add and import?

Is this a real concern? Do we have any data to back this claim up?

**Comment by rokroskar** [comment]
> It assumes that users are well-versed in DOIs

I don't think so - there is nothing DOI specific. It's more a matter of using a published dataset or just a dataset that someone else prepared vs. something that I cook up. I doubt it's hard to see that distinction.

**Comment by cchoirat** [comment]
> I doubt it's hard to see that distinction.

I'm not saying it's hard.  I'm wondering whether it matters for end-users.

**Comment by pameladelgado** [comment]
Leaving DOIs aside, as a user of any tool/software I find it useful to have a difference between when I'm importing a project/data/whatever than when I'm creating new content. Granted, the tools that I use(d) that have the `Import` functionality do import the whole thing, in this case the project.

>One could also think that import has to do with adding units of data to a dataset.
I would definitely not think of that if somebody says import.

Also, what would happen to the lineage if some data is imported? will it be wiped out? if the lineage would still be there somehow then we definitely need to differentiate between adding new content and importing existing content.

**Comment by rokroskar** [comment]
> Also, what would happen to the lineage if some data is imported? will it be wiped out? if the lineage would still be there somehow then we definitely need to differentiate between adding new content and importing existing content.

Yes, if data is added or a dataset imported from a renku repository, the lineage will be preserved.

**Comment by pameladelgado** [comment]
Normally tools use import when the content you are adding is not 'clean'. Think of an IDE, you can create a new project and `add` files to it `creating` new content for the project; instead if you have another project created that the IDE added and knows how to read (in our case the lineage) and you `import` it, you are effectively not creating new content, just importing it.
For me, the word `create` implies its new and that hasnt existed before.
Actually, I would find it confusing if I `create` data for my project and suddenly there's some info asociated to it like the lineage that I dont know about.

**Comment by jsam** [comment]
Here is my proposal with some structure. 
The structure which I'm trying to follow is `renku <resource> <operation>`. Since most of the operations of importing and exporting are going to interact with some external resource, we most likely want to do them in an async manner (since they might take a long time and we don't want to overtake users shell).

So the proposal is:
```
renku service import [file|dataset|algorithm]
renku service export [file|dataset|algorithm]
renku service status

renku file [add|ls|rm|edit] or renku data [add|ls|rm|edit]
renku datasets [new|add|ls|rm|edit]
```

And the reasoning behind is the following.

# Background service for import & export
Import brings only *external resource* to the repository. That external resource can be some random object with no metadata (a file), might be a dataset which comes from some provider (a dataset) or it might be some other algorithm which somebody else wrote and shared (TBD in future - a reproducible & shareable algorithm/workflow). 

The big sister to import command is export. It can package files contained into archives and help with distributing them to some 3rd party location. Can export datasets to providers. Can package and ship algorithms which people want to share and ship them to.

Moving import/export actions behind a service resource makes a clean user experience as well since those jobs usually can take a pretty long time to complete (so blocking users shell doesn't make much sense).

# file or data
Inspired from @rokroskar data command. Atomic units representing just data elements which are being processed or contained in bigger containers (datasets). User can list all files within a repository, can remove files from the repository or move them around (just like in git). Files contain metadata about themselves (and lineage could be tracked if possible), which, a subset of, user can edit at any time.

Introducing this subcommand provides nicer user experience for managing just data and more importantly giving user ability to edit the metadata more granularly. 

  * `add` adds metadata about the file. Can be user-provided metadata or metadata pulled from some source.
  * `rm` removes the file from the repository (including the metadata)
  * `ls` list all files register within Renku repository
  * `edit` gives the user the ability to edit a subset (editable part) of metadata
 
# datasets
Logical aggregation of files/data under the same name and metadata which is versioned. User can *add only a local file/data* which he previously imported.

Follows the same interface as a data resource for easier interaction:
  * `add` adds only local files into a dataset
  * `rm` removes a file from a dataset (this solves the current problem which we have with confusion between rm and unlink)
  * `ls` lists all or subset of files from the repository
  * `edit` gives a user ability to edit only dataset metadata (excluding dataset file metadata). Separating those 2 edit operations provides much nicer experience since dataset can have hundreds of files and in current Renku editing all at once is painful.


Now with this structure, I see both vertical and horizontal ability to extend very easily with the new features. It addresses the current problems (including a clean separation between add and import). All commands are following the same pattern so it's intuitive to navigate through.

**Comment by ciyer** [comment]
It would be helpful to see a few concrete examples. What sequence of commands would do the following?

- Create a dataset called flights and add data from the url https://www.dropbox.com/s/m23jq5v985dmqtt/2019-01-flights.csv.zip?dl=0
- Create a dataset called flights and add data from the project https://renkulab.io/projects/612/
- Create a dataset called flights and add data located at ~/Downloads/2019-01-flights.csv.zip (not a repository)
- Create a dataset called flights and add data located at data/raw/2019-01-flights.csv.zip (in the repository)

**Comment by rokroskar** [comment]
I like the idea of tying the subcommands to entities that Renku knows about. But why do we need the `service` subcommand? Can't you just have, for example, 

```
renku data [add|import|ls|rm|edit]
```

The user doesn't necessarily need to know how the import is happening.

**Comment by jsam** [comment]
The service or daemon is considered a resource, and we are following the proposed pattern of resource and action. From my point of view a good practice is that user is aware of additional service which we manage for him in the background, so masking that away completely so he's not aware of it, is a bad thing. Another point why separated is better is that we are trying to address the issue you brougth up and thats minimizing confusion between add and import.

@ciyer I will provide examples a bit later.

**Comment by rokroskar** [comment]
> The service or daemon is considered a resource

I'm not sure the user would care tbh - I was thinking of "resources" more like the primary "entities" that make it to the KG. I also would not bring the potential client/server architecture question into this discussion but would rather keep it quite separate.

**Comment by erbou** [comment]
My understanding is that _service_ is only used to provide a hint to the user - and this could also be conveyed in the output of the command, e.g. with a message containing a job number that can be used to check its status.

**Comment by erbou** [comment]
> I think the differentiation comes about because in the case of add we are creating new content, i.e. new metadata and in the case of import we are keeping it as is

I had misunderstood your comment, because I took the _import = create + add_ too literally, but they are different. I am now in favor of having both `import` and `create`.

If I have:

* Create a new dataset
       - empty constructor:  __`renku dataset create`___`dataset`_
       - copy constructor:   __`renku dataset create --from`___`url [dataset]`_
* Add data to that dataset:  __`renku dataset add-data`___`url+ dataset`_

Then as a user I expect a consistent behavior from this dataset object. In particular, I should be able to add new files regardless of the method I used to create it.

On the other hand, if we want to prevent local modifications on an imported dataset (e.g. you cannot add or remove files to it, or change the meta-data), then it makes sense to use a different command name, such as __`renku import`___`url [dataset]`_ to make it clear that the dataset you are about to create will be special, that is: a reference to a remote dataset that can be updated, but cannot be altered locally.

In either case, it should be possible to consider the case of a dataset composed of multiple imported (and immutable) datasets, e.g.:

"Each canton maintains a dataset of observations from weather stations (all respecting the same schema) that they use for weather reports at the canton level. We want to import them all into a single dataset that we can use to compute weather reports at the national level. And, optionally, we may want to experiment with various subsets of this composite dataset by adding or removing datasets from selected cantons."

Would that be possible?

**Comment by erbou** [comment]
Are we missing`mv`, it is never mentioned. Can we add it to the list of file commands?

**Comment by rokroskar** [comment]
> On the other hand, if we want to prevent local modifications on an imported dataset (e.g. you cannot add or remove files to it, or change the meta-data), then it makes sense to use a different command name, such as renku importurl [dataset] to make it clear that the dataset you are about to create will be special, that is: a reference to a remote dataset that can be updated, but cannot be altered locally.

Yes, this is along the lines of what I was thinking. Keep in mind that in our current abstraction, it's very much possible to import a dataset and then add the files that belong to that dataset to another dataset that you created. This would serve your example of cantonal weather observations, for example. In the KG it would still be very much possible to trace the origin of those data back to the original datasets. 

> Why are we missing `mv`

Just simplifying things for now... :)

**Comment by jsam** [comment]
@ciyer here are the usage patterns for use cases you asked for. Please note, that in the following usage patterns I have renamed `service` to `remote`.

### 1.
> Create a dataset called flights and add data from the url https://www.dropbox.com/s/m23jq5v985dmqtt/2019-01-flights.csv.zip?dl=0

This use case is 2 step: 
  1) Bring remote data (without metadata) locally, and 
  2) Add local extracted (due to passed flag from step 1.) data to dataset flights. If the dataset does not exist it is created if it exists the version is automatically incremented.
```
>> renku remote import https://www.dropbox.com/s/m23jq5v985dmqtt/2019-01-flights.csv.zip?dl=0 --extract
>> renku remote status
JOB_ID   EXECUTED_AT        TYPE    PROGRESS
------   -----------        ----    --------
adf323df  22.07.2019 07:37  import   100%

>> renku dataset add flights 2019-01-flights.csv
>> renku dataset ls
ID        DISPLAY_NAME    VERSION    CREATED          CREATORS
----      --------------  ---------  ---------        ----------
sdffgf23   flights         0.1.0     22.07.2019 7:38  sam
```

One thing to note here is that `import` is an async operation which is very nice since it gives us the ability to execute the long-running operation in the background without overtaking users shell and to do error handling in a much elegant manner. For example, if downloading a 50GB fails for some reason, service could have an auto-retry ability to try again.

### 2.
>> Create a dataset called flights and add data from the project https://renkulab.io/projects/612/

This is the most complicated use case we have to solve and it involves solving a couple of problems. 
      1) Discovery of datasets (and future workflows/algorithms) - giving user ability to cherry-pick parts of the remote project and bring it in its own project
      2) Importing the selected resource

```
>> renku remote add awesome-project https://renkulab.io/projects/612/
>> renku remote ls awesome-project
PROJECT_ID PROJECT_ALIAS RESOURCE NAME VERSION 
----------      ---------     -------- ----- -------
612 awesome-project dataset     flights-dataset   0.1.0
612 awesome-project dataset     flights-dataset   0.1.2
612 awesome-project dataset     flights-dataset   0.1.3
612 awesome-project dataset     flights-dataset   0.1.4
612 awesome-project algorithm  flights-analysis  0.1.0
612 awesome-project algorithm  flights-analysis  0.1.1

>> renku remote import awesome-project flight-dataset:0.1.4
>> renku dataset ls
ID        DISPLAY_NAME    VERSION    CREATED          CREATORS
----      --------------  ---------  ---------        ----------
dfgfgf23   flight-dataset         0.1.4     22.07.2019 7:44  sam
```

A worthy thing to note here is that since all metadata from destination project needs to be imported along with the dataset/algorithm, no `add` operation is needed (since we need to pull the metadata along with the actual resource).

### 3. 
>> Create a dataset called flights and add data located at ~/Downloads/2019-01-flights.csv.zip (not a repository)

```
renku dataset add flights ~/Downloads/2019-01-flights.csv.zip --extract
```
This creates a dataset and adds extracted data to the repository. This will copy the data from downloads into specified data-dir inside the repository.

### 4.
>> Create a dataset called flights and add data located at data/raw/2019-01-flights.csv.zip (in the repository)

```
renku dataset add data/raw/2019-01-flights.csv.zip
```

For 3. and 4. it would also be possible to attach metadata to flights without actually grouping them into a dataset. For that we would use the following command:

```
renku file add ~/Downloads/2019-01-flights.csv.zip --extract
renku file add data/raw/2019-01-flights.csv.zip --extract
```

Of course, this implies that we would need to have a seamless integration between file and dataset (metadata and interface wise). File resource, in this case, adds a fine granular control whereas dataset gives us a container type functionality.

**Comment by erbou** [comment]
@jsam 

* The async operations is a nice feature. What is the worse that could happen (corner cases), if I keep working during the download?

* It seems that `remote import` could mean different things depending on its arguments: In 1. download a file (without metadata), In 2. import a dataset. Shouldn't the file import be called `get` to prevent any confusions?

* Is `remote` truly polymorphic, to the extent that I can `add` a Zenodo DOI, and expect the `ls` and `import` operations to work the same as they would on a remote renku resource? Or should I use another form of method 1, or a 3rd method (details?) to import from a non-renku remote? 

* In 2. most of the time, I will not want to import a _pinned_ version of a dataset. I will want the `latest` version, and be confident that it will be automatically updated without the need for subsequent import operations, (i.e. `renku update` should use the latest).

* Side question: in 2. is `created`, and `author` taken from the (newly created) local dataset or the remote dataset?

* Side question: in 4, how do you infer that the name of the dataset should be `flight`. Do you expect a meta data in the zip file? or is it from the zip filename?

**Comment by ciyer** [comment]
@erbou After taking with Sam, I realized that we are talking about two different things here. If we think of the CLI as decomposed into "plumbing" and "porcelain" commands, where plumbing are the internals and porcelain are what users typically use, Sam is proposing plumbing, and I (and probably you as well) are talking about porcelain.

**Comment by jsam** [comment]
1) If the push fails, we create a PR?
2) I think those are different operations, so yes they should be under different commands.
3) Yes, they should be.
4) Once we have import as an async operation we could think about different configuration options we could use. I would keep workflow stuff as a separate vertical and not have to update under the same command as updating workflows since both of them are potentially very long-running operations.

1. Should be both.
2. On import either it is in metadata or user specifies it.

**Comment by rokroskar** [comment]
I like the idea of having a remote from which you can pick and choose pieces to import - this would reflect the experience one would get browsing projects in the UI and potentially importing datasets and/or workflows etc. So the proposal in https://github.com/SwissDataScienceCenter/renku/issues/593#issuecomment-513670281 looks good to me, though I think a sticky point might still be the semantics of `import` - in the case of importing from a remote (non-renku) URL the end result is different from an import from a renku "remote".

**Comment by Panaetius** [comment]
I don't think `dataset add` should create a dataset unless explicitly told so by the user (with e.g. a `--create` flag). Otherwise a user might misspell the name of the dataset, the command still succeeds but the user is left confused. It'd be better with a flag and informing the user of the existence of the flag and failing if it's not supplied.

Async in the server (plumbing) (especially concerning the UI) makes sense. I'm not so sure concerning the CLI (porcelain). It raises complexity for us and the user a bit, is not that standard compared to most (shell) commands and one can already send a command to the background by appending `&` (or just open multiple terminals). Plus it'd make it more difficult to use the renku command in a script. It really depends on the circumstances. If the download takes <5 minutes and I'm not doing anything anyways, I'd find it frustrating to have to check the status manually every 10 seconds to see if it finished, but if it takes 5 hours I won't wait, so running it in the background could be a nice option. Maybe we could allow the user to chose between async/sync with a flag? Also in a lot of real world settings datasets tend to be rather small, unfortunately.

`remote add` and `remote import` are a bit misleading. In this context `import` can be misunderstood as importing a remote, instead of the intended meaning of importing data from an already added remote. At least it'd break the Resource->Action paradigm. Maybe `remote add` to add a remote source and `dataset pull` to get data from a remote?

**Comment by Panaetius** [comment]
@pdurbin Great, I'm glad you got it working :smile:

We do not support resolution of `hdl:` URIs at the moment, so just using the `hdl:...` wont work. We can definitely add a feature request for that.

Theoretically it could work with the full url `https://data.cimmyt.org/dataset.xhtml?persistentId=hdl:11529/10016`, but it seems there's some error on Dataverse's end for this.

I think discussing the details of how the import works right now would help in discussing this and future changes. There's 2 different cases, importing a doi and importing a full Dataverse URL:
* Importing a doi: 
  - The parameter is recognized as a doi
  - The doi is resolved to a (possibly Dataverse) URL using `http://doi.org/...`
  - The URl gets tested on if it's a Dataverse instance or not (by using the `api/info/version` endpoint
  - If it is a Dataverse instance, an export URL is made of the form `https://data.cimmyt.org/api/datasets/export?exporter=schema.org&persistentId=<doi>`
  - The Dataset is imported using this URL

* Importing a URL:
  - Basically the same as above, except for the first 2 steps

Since we don't have functionality to resolve `hdl:`, the import fails to find a valid import provider when it fails to resolve. But if you instead supplied the full URL, e.g. `https://data.cimmyt.org/dataset.xhtml?persistentId=hdl:11529/10016` for your example, it should still be able to check if we're dealing with a Dataverse instance, extract the persistent id and export from there. Unfortunately, `https://data.cimmyt.org/api/datasets/export?exporter=schema.org&persistentId=hdl%3A11529%2F10016` doesn't seem to work for exporting the dataset and the import fails, yielding an `{"status":"ERROR","message":"Export Failed"}` error. But it's a good test as the CLI just reports `Uri not found` instead of something like `Dataverse Error: Export Failed` which would be more useful for users, i.e. it'd be good to have a bit more verbose error reporting.

It is unclear to me why that export doesn't work, though. Maybe you can shed some light on it?

When I implemented the feature, I tried it with several Dataverse instances listed [here](https://en.wikipedia.org/wiki/Dataverse#Dataverse_Installations_Around_the_World). Of those that I tested, all instances that use Handle didn't seem to have a valid Dataverse API set up, and the ones that had a working API endpoint all used doi's for their datasets, so I assumed the Handle ones use an older version of Dataverse without API or are some edge case that doesn't support exporting via API. And without any instance to test it, it wouldn't have made sense to implement.

It would be great if you could add a working Dataverse API instance that uses Handle's/a working test Handle for a follow-up issue adding Handle support.

As for documentation, I agree that it's lacking. We are currently redesigning the renku CLI, affecting most commands, so the documentation will get a big overhaul as well. So we didn't want to invest a lot of time in the documentation right now.It might also make sense to hold off on adding renku to the supported integrations until our documentation actually reflects the change :relaxed:

**Comment by pdurbin** [comment]
> It is unclear to me why that export doesn't work, though. Maybe you can shed some light on it?

Well, that "schema.org" exporter you're using is relatively recent, added in Dataverse 4.10 (in https://github.com/IQSS/dataverse/pull/5169 for my reference). It looks likes that's how you're getting the list of files. If you go to https://data.cimmyt.org/api/info/version you'll see that they're still on Dataverse 4.7.1. That said, it's also possible for Dataverse installations to turn off "exposing" the file download URLs with a setting called "dataverse.files.hide-schema-dot-org-download-urls" ( http://guides.dataverse.org/en/4.16/installation/config.html#dataverse-files-hide-schema-dot-org-download-urls ). So to summarize:

- You can only get file listings from the "schema.org" exporter if the version of Dataverse is 4.10 or higher.
- Even if the version of Dataverse is new enough to have the "schema.org" exporter, it's possible for the installation to hide them from the output. The work around in this case would be to get the file IDs from the "dataverse_json" exporter.

You can visually see which exporters are available by clicking "Metadata" and then "Metadata Exports" like in the screenshot below.

![Screen Shot 2019-08-29 at 1 34 17 PM](https://user-images.githubusercontent.com/21006/63963376-e5a65600-ca62-11e9-9e26-ab60a2d81ff4.png)

If I can find a "hdl:" dataset in the wild for you to test with, I'll ping you. 😄 

If you want we can move this Dataverse-specific discussion to another issue or http://chat.dataverse.org or elsewhere but since you mentioned a couple other things, I'll keep going. 😄 

https://en.wikipedia.org/wiki/Dataverse#Dataverse_Installations_Around_the_World is cool but our "official" list of Dataverse installations around the world is at https://services.dataverse.harvard.edu/miniverse/map/installations-json . This powers the map on https://dataverse.org . I'm not sure how stable that URL is but it's what we have right now. I make a backup of that JSON file here: https://github.com/IQSS/dataverse-metrics/blob/v0.2.6/update-all-installations-list.sh 

I'd say you should go ahead and create an issue about the integration at https://github.com/IQSS/dataverse/issues . I know it's early days but this way the Dataverse community might try it out and give you feedback. I also let them know in this post on our mailing list: https://groups.google.com/d/msg/dataverse-community/2H21moBIRgU/PUuai7UNBgAJ . I suspect that Renku will be new to most of them. 😄 

Again, great stuff! Thanks!!

**Comment by rokroskar** [comment]
Hey @pdurbin thanks for the detailed info - at this point I think it would be best to pick it up in another issue so it doesn't get lost in the noise here.

**Comment by rokroskar** [comment]
In the interest of moving forward here, we discussed this in person yesterday. The main conceptual point of conflict is the different assumptions about what a `Dataset` represents - this should be fixed in the documentation. By `Dataset` we mean 

> a grouping of one or more data files for a particular purpose with optional additional metadata. 

The [schema.org definition](https://schema.org/Dataset) is simply:

> A body of structured information describing some topic(s) of interest. 

Our use of `Dataset` is consistent with e.g. Zenodo where the `Dataset` is an abstraction which contains descriptions of the purpose/topic and the detailed locations of where to retrieve the actual data (files) that comprise the `Dataset`. 

Our view is that the user may bring data into the project and optionally group it into a `Dataset` if that makes sense for a particular analysis or project, especially if the aim is to share the data and to easily communicate which data is needed to reproduce a particular result. The `Dataset` should be a convenient metadata "container" for data that doesn't care about a particular organization of data on disk (e.g. is agnostic to directory structure apart from providing some sensible defaults). We should provide convenience commands asap for using data that is grouped into a `Dataset` to make the utility of this concept more obvious. 

We discussed that there were the following possibilities for bringing data into the renku project:

* from a local file
* from a local git repository
* from a remote URL 
* from a remote git repository
* from another renku project 

In addition, one should be able to import entire datasets from external sources with all of the associated metadata. This is currently supported with the `renku dataset import` command and works for zenodo and dataverse. 

Other considerations:

* when adding data from another git repository, one should be able to specify a specific path to import (e.g. `data/file` within the repo, or just `data/` for all the files within the `data` directory)
* the user should be able to specify the destination path of the added data - by default, this is the `data/<dataset>` directory
* adding data to a `Dataset` should not be a requirement for bringing data into the renku project. We should provide a convenience command that simply copies the data into the project and adds tracks it with LFS. The user may at a later point add this data to a `Dataset`. 

So to answer the question from @ciyer it should look like:

1. Create a dataset called flights and add data from the url https://www.dropbox.com/s/m23jq5v985dmqtt/2019-01-flights.csv.zip?dl=0

```
renku dataset create flights
renku dataset add flights https://www.dropbox.com/s/m23jq5v985dmqtt/2019-01-flights.csv.zip?dl=0
```

Using the suggestion from @Panaetius it could also be done in one step:

```
renku dataset add --create flights https://www.dropbox.com/s/m23jq5v985dmqtt/2019-01-flights.csv.zip?dl=0
```

2. Create a dataset called flights and add data from the project https://renkulab.io/projects/612/

Since the UI has changed from using IDs for projects to namespaces/names, I think it would look like this (assuming the data is in the `data/flights` subdirectory of the source repo):

```
renku dataset add --create flights --path data/flights git+ssh://renkulab.io/<namespace>/<project-name>
```

or

```
renku dataset add --create flights --path data/flights git+https://renkulab.io/gitlab/<namespace>/<project-name>
```

3. Create a dataset called flights and add data located at ~/Downloads/2019-01-flights.csv.zip (not a repository)

```
renku dataset add --create flights ~/Downloads/2019-01-flights.csv.zip (not a repository)
```

4. Create a dataset called flights and add data located at data/raw/2019-01-flights.csv.zip (in the repository)

```
renku dataset add --create flights data/raw/2019-01-flights.csv.zip
```

Those commands will add the data to `data/flights` but the user could optionally specify a `--dst` flag to override this default.
