### ISSUE TITLE
Documentation Structure

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku#626]
# Description

We need to provide a better introduction to Renku. This should be adopted on:
- the landing page of renkulab.io
- the hands-on tutorial
- the landing page for the renku github repo
- the documentation on readthedocs
- landing page for the renku project on the SDSC website

# Content

We should introduce Renku by starting with the five FAQs in data-driven research
- How did I compute this result?
- How does new data change this result?
- How did *you* compute your result? Can I use your code/data to reproduce it?
- Has anyone ever used [algorithm] on this kind data? What are the results?
- Who is using these data and algorithms in what context?

To answer these questions, we need to answer more fundamental questions:
- Where do I get the code and data?
- What environment does this code run in?
- How are code and data connected together to arrive at the final result?
- How did the code and data evolve?
- What does the code do? How is the data structured?

The latter questions can be answered by tools (E.g. *Docker* for the environment, *git* for the code evolution, etc). We should explain how renku combines these tools.

We should create graphical representations of these to make them more effective.

# See also https://docs.google.com/document/d/1y9_xE2XkxjeWS_eun49Tj1scVwYOzLt1l5GNWTXgE48/edit

**Comment by Panaetius** [comment]
Not sure if this issue is the right place for it, but we could consolidate documentation by using intersphinx with some smart menu logic. 

Basically, https://renku-python.readthedocs.io/en/latest/ and https://renku.readthedocs.io/en/latest/ don't reference each other, so some instructions (e.g. installing the CLI) are duplicated and one can't easily go from one documentation to the other one.

I solved this in the mlbench project https://mlbench.readthedocs.io/en/latest/ by having the docs from different repos as subprojects in readthedocs and using a script to generate the sidebar ( https://github.com/mlbench/mlbench-docs/blob/develop/gensidebar.py ), this way the entries under "Components" lead to the documentation of different repos, but it's not apparent to the user that the documentation is spread out, it handles as if there was just a single readthedocs instance. And with intersphinx, linking between them is relatively easy as well.

Maybe we could adopt something like this for renku & renku-python?

**Comment by rokroskar** [comment]
This would be great and we should definitely do it!

**Comment by rokroskar** [comment]
I was confused by the title of this issue - can this go under #544? We can put it under the common heading of "Restructure introductory renku material"

**Comment by emmjab** [comment]
Notes from the meeting on restructuring the documentation:
(https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/50987017/Documentation+Restructuring)

Other docs we talked about:
* https://docs.metaflow.org/
* https://docs.docker.com/get-started/

Sections to start with:
* Structure of the docs @rokroskar 
* Why Renku? (5 FAQs and something about templated & versioned environments for courses, labs, etc.) @rokroskar [maybe implemented as a carousel for different use cases]
* What is Renku? (version control, environments/containers, lineage - reuse text & visuals) @emmjab 
* Tutorial (partitioned into sections that we can pull out into separate pages) @ciyer 

Other sections to restructure the current docs into:
* Release notes
* Roadmap
* Get in Touch
* Getting Started
* Installation
* Tutorial
