### ISSUE TITLE
SHACL schema to be available for Renku services

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku#685]
As a Renku owner, I'd like SHACL schemas for validation of triples used in Renku to be available for the Renku services.

Acceptance criteria:
* find the best-suited storage for the schemas so it:
  * allow requesting different versions;
  * allow versioning to be aligned with renku-python versions;
  * be accessible for the travis builds;
  * be accessible for local dev builds;

**Comment by rokroskar** [comment]
We made a repo for the purpose of serving the renku ontology a long time ago: https://github.com/SwissDataScienceCenter/renku-ontology/

The idea was that we would serve the ontology in turtle format via the github pages. Since we abandoned developing our own ontology but instead resorted to using existing vocabularies as much as possible, this was dropped for the time being. However, we could re-purpose it for the SHACL shape graphs.
